name: thunder_creator
description: This project is a Flutter application scaffolded with GetX and follows the MVC (Model-View-Controller) architecture.
version: 1.0.2
repository: https://github.com/AbdAlftahSalem/Thunder-Creator.git
homepage: https://github.com/AbdAlftahSalem/Thunder-Creator.git

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  args: ^2.2.2
  get: ^4.6.5
  logger: ^2.0.2

executables:
  thunder_creator:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
