name: thunder_cli
description: This project is a Flutter application scaffolded with GetX and follows the MVC (Model-View-Controller) architecture.
version: 2.3.4+2
repository: https://github.com/AbdAlftahSalem/Thunder-CLI
homepage: https://github.com/AbdAlftahSalem/Thunder-CLI

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  args: ^2.2.2
  translator: ^1.0.0
  dio: ^5.3.2

executables:
  thunder:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
